const cartPageStyles = {
  page: {
    maxWidth: "1180px",
    margin: "0 auto 3rem",
    padding: "0 1.5rem",
    color: "#2d241f",
  },
  hero: {
    padding: "2rem",
    borderRadius: "28px",
    marginBottom: "1.5rem",
    background:
      "radial-gradient(circle at top left, rgba(255,245,228,0.95), rgba(231,205,170,0.92) 48%, rgba(98,69,44,0.9) 100%)",
    color: "#2b170a",
    boxShadow: "0 18px 48px rgba(103, 72, 36, 0.16)",
  },
  eyebrow: {
    margin: "0 0 0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    fontSize: "0.75rem",
    fontWeight: "700",
  },
  title: {
    margin: "0 0 0.75rem",
    fontSize: "clamp(2rem, 4vw, 3.4rem)",
    lineHeight: 1.05,
  },
  subtitle: {
    maxWidth: "720px",
    margin: 0,
    fontSize: "1.05rem",
    lineHeight: 1.7,
  },
  status: {
    padding: "2rem",
    textAlign: "center",
    color: "#6b5a4f",
  },
  error: {
    color: "#b42318",
    marginBottom: "1rem",
  },
  emptyState: {
    padding: "2rem",
    borderRadius: "24px",
    backgroundColor: "#fffaf2",
    border: "1px solid #ecdcc8",
    textAlign: "center",
  },
  emptyTitle: {
    margin: "0 0 0.75rem",
    fontSize: "1.7rem",
  },
  emptyText: {
    margin: "0 0 1rem",
    color: "#5f5147",
    lineHeight: 1.7,
  },
  primaryLink: {
    display: "inline-block",
    padding: "0.9rem 1.25rem",
    borderRadius: "999px",
    backgroundColor: "#7f4f24",
    color: "#fffaf4",
    textDecoration: "none",
    fontWeight: "700",
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 2fr) minmax(280px, 1fr)",
    gap: "1.5rem",
    alignItems: "start",
  },
  itemsPanel: {
    display: "grid",
    gap: "1rem",
  },
  itemCard: {
    display: "grid",
    gridTemplateColumns: "160px minmax(0, 1fr)",
    gap: "1rem",
    padding: "1rem",
    borderRadius: "24px",
    backgroundColor: "white",
    border: "1px solid #ecdcc8",
    boxShadow: "0 12px 32px rgba(67, 41, 18, 0.08)",
  },
  imageWrap: {
    minHeight: "160px",
    borderRadius: "20px",
    overflow: "hidden",
    background:
      "linear-gradient(135deg, rgba(255,245,228,0.95), rgba(240,216,183,0.92))",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  placeholder: {
    height: "100%",
    display: "grid",
    placeItems: "center",
    color: "#8d6f55",
    fontWeight: "700",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  itemBody: {
    minWidth: 0,
  },
  itemHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
    marginBottom: "0.75rem",
  },
  category: {
    margin: "0 0 0.35rem",
    color: "#7f4f24",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: "0.75rem",
  },
  itemTitle: {
    margin: 0,
    fontSize: "1.25rem",
  },
  itemPrice: {
    fontSize: "1.1rem",
    color: "#6a3f19",
  },
  stockText: {
    margin: "0 0 1rem",
    color: "#5f5147",
  },
  itemFooter: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap",
  },
  quantityGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  quantityLabel: {
    fontWeight: "700",
    color: "#6b492e",
  },
  quantityInput: {
    width: "96px",
    padding: "0.7rem 0.8rem",
    borderRadius: "14px",
    border: "1px solid #cdb597",
    fontSize: "1rem",
  },
  subtotal: {
    marginLeft: "auto",
    fontSize: "1.05rem",
  },
  removeButton: {
    padding: "0.75rem 1rem",
    borderRadius: "999px",
    border: "1px solid #d7b7a0",
    backgroundColor: "#fff7f2",
    color: "#8a3922",
    cursor: "pointer",
    fontWeight: "700",
  },
  summaryCard: {
    padding: "1.5rem",
    borderRadius: "24px",
    backgroundColor: "#fffaf2",
    border: "1px solid #ecdcc8",
    position: "sticky",
    top: "1.5rem",
  },
  summaryLabel: {
    margin: "0 0 1rem",
    color: "#7f4f24",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    fontSize: "0.8rem",
    fontWeight: "700",
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
    marginBottom: "0.9rem",
    color: "#4f4035",
  },
  checkoutButton: {
    display: "block",
    textAlign: "center",
    textDecoration: "none",
    width: "100%",
    marginTop: "0.75rem",
    padding: "0.95rem 1.1rem",
    borderRadius: "999px",
    border: "none",
    backgroundColor: "#7f4f24",
    color: "#fffaf4",
    fontWeight: "700",
  },
  clearButton: {
    width: "100%",
    marginTop: "0.75rem",
    padding: "0.95rem 1.1rem",
    borderRadius: "999px",
    border: "1px solid #cdb597",
    backgroundColor: "white",
    fontWeight: "700",
    cursor: "pointer",
  },
};

export default cartPageStyles;
