const checkoutPageStyles = {
  page: {
    maxWidth: "1180px",
    margin: "0 auto 3rem",
    padding: "0 1.5rem",
    color: "#2d241f",
  },
  hero: {
    padding: "2rem",
    borderRadius: "28px",
    marginBottom: "1.5rem",
    background:
      "radial-gradient(circle at top left, rgba(255,245,228,0.95), rgba(233,213,186,0.92) 46%, rgba(108,74,48,0.9) 100%)",
    color: "#2b170a",
    boxShadow: "0 18px 48px rgba(103, 72, 36, 0.16)",
  },
  eyebrow: {
    margin: "0 0 0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
    fontSize: "0.75rem",
    fontWeight: "700",
  },
  title: {
    margin: "0 0 0.75rem",
    fontSize: "clamp(2rem, 4vw, 3.4rem)",
    lineHeight: 1.05,
  },
  subtitle: {
    maxWidth: "720px",
    margin: 0,
    fontSize: "1.05rem",
    lineHeight: 1.7,
  },
  status: {
    padding: "2rem",
    textAlign: "center",
    color: "#6b5a4f",
  },
  error: {
    marginBottom: "1rem",
    color: "#b42318",
    fontWeight: "700",
  },
  success: {
    marginBottom: "1rem",
    color: "#217a4c",
    fontWeight: "700",
  },
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.4fr) minmax(300px, 1fr)",
    gap: "1.5rem",
    alignItems: "start",
  },
  formCard: {
    padding: "1.5rem",
    borderRadius: "24px",
    backgroundColor: "#fffaf2",
    border: "1px solid #ecdcc8",
  },
  summaryCard: {
    padding: "1.5rem",
    borderRadius: "24px",
    backgroundColor: "white",
    border: "1px solid #ecdcc8",
    boxShadow: "0 12px 32px rgba(67, 41, 18, 0.08)",
  },
  sectionTitle: {
    margin: "0 0 1rem",
    fontSize: "1.35rem",
  },
  field: {
    display: "grid",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  label: {
    fontWeight: "700",
    color: "#6b492e",
  },
  input: {
    width: "100%",
    padding: "0.9rem 1rem",
    borderRadius: "14px",
    border: "1px solid #cdb597",
    fontSize: "1rem",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "0.9rem 1rem",
    borderRadius: "14px",
    border: "1px solid #cdb597",
    fontSize: "1rem",
    resize: "vertical",
    boxSizing: "border-box",
  },
  submitButton: {
    width: "100%",
    padding: "0.95rem 1.25rem",
    borderRadius: "999px",
    border: "none",
    backgroundColor: "#7f4f24",
    color: "#fffaf4",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "1rem",
  },
  summaryItems: {
    display: "grid",
    gap: "0.9rem",
    marginBottom: "1rem",
  },
  summaryItem: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
  },
  itemName: {
    margin: "0 0 0.2rem",
    fontWeight: "700",
  },
  itemMeta: {
    margin: 0,
    color: "#5f5147",
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
    paddingTop: "1rem",
    borderTop: "1px solid #ecdcc8",
    fontSize: "1.05rem",
  },
  emptyState: {
    padding: "2rem",
    borderRadius: "24px",
    backgroundColor: "#fffaf2",
    border: "1px solid #ecdcc8",
    textAlign: "center",
  },
  emptyTitle: {
    margin: "0 0 0.75rem",
    fontSize: "1.7rem",
  },
  emptyText: {
    margin: "0 0 1rem",
    color: "#5f5147",
    lineHeight: 1.7,
  },
  primaryLink: {
    display: "inline-block",
    padding: "0.9rem 1.25rem",
    borderRadius: "999px",
    backgroundColor: "#7f4f24",
    color: "#fffaf4",
    textDecoration: "none",
    fontWeight: "700",
  },
  secondaryLink: {
    display: "inline-block",
    marginTop: "1rem",
    color: "#7f4f24",
    fontWeight: "700",
    textDecoration: "none",
  },
};

export default checkoutPageStyles;
