const navBarStyles = {
  nav: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 2rem",
    borderBottom: "1px solid #e7dccd",
    marginBottom: "2rem",
    background:
      "linear-gradient(135deg, rgba(255,246,233,0.98), rgba(247,233,213,0.92))",
  },
  leftGroup: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap",
  },
  rightGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.9rem",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  brand: {
    marginRight: "0.5rem",
    textDecoration: "none",
    color: "#472d1b",
    fontWeight: "800",
    letterSpacing: "0.04em",
  },
  link: {
    textDecoration: "none",
    color: "#5c4634",
    fontWeight: "600",
  },
  accountMeta: {
    display: "grid",
    gap: "0.15rem",
    textAlign: "right",
  },
  roleText: {
    color: "#7b6758",
    fontSize: "0.82rem",
    fontWeight: "700",
  },
  authLinkGroup: {
    display: "flex",
    alignItems: "center",
    gap: "0.85rem",
  },
  authLinkButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "92px",
    padding: "0.55rem 1rem",
    borderRadius: "999px",
    border: "1px solid #d7c0a1",
    backgroundColor: "#fffaf3",
    color: "#5c4634",
    fontWeight: "700",
    textDecoration: "none",
  },
  email: {
    color: "#6b5a4f",
    fontWeight: "600",
  },
  button: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
    borderRadius: "999px",
    border: "1px solid #c9a982",
    backgroundColor: "#fff8ef",
  },
  menuWrap: {
    position: "relative",
  },
  menuTrigger: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.45rem",
    padding: "0.55rem 0.95rem",
    borderRadius: "999px",
    border: "1px solid #d7c0a1",
    backgroundColor: "#fffaf3",
    color: "#5c4634",
    fontWeight: "700",
    cursor: "pointer",
  },
  menuChevron: {
    fontSize: "0.75rem",
    color: "#8a705a",
  },
  menuPanel: {
    position: "absolute",
    top: "calc(100% + 0.65rem)",
    left: 0,
    minWidth: "220px",
    padding: "0.55rem",
    borderRadius: "18px",
    border: "1px solid #e5d2ba",
    backgroundColor: "#fffdf8",
    boxShadow: "0 18px 44px rgba(76, 53, 29, 0.14)",
    zIndex: 20,
  },
  menuTitle: {
    padding: "0.55rem 0.7rem 0.35rem",
    color: "#8c745f",
    fontSize: "0.75rem",
    textTransform: "uppercase",
    letterSpacing: "0.12em",
    fontWeight: "700",
  },
  menuLink: {
    display: "block",
    padding: "0.8rem 0.85rem",
    borderRadius: "12px",
    textDecoration: "none",
    color: "#4c3a2b",
    fontWeight: "600",
  },
};

export default navBarStyles;
