const sellerPageStyles = {
  page: {
    maxWidth: "1180px",
    margin: "0 auto 3rem",
    padding: "0 1.5rem",
    color: "#2d241f",
  },
  hero: {
    padding: "2rem",
    borderRadius: "28px",
    marginBottom: "1.5rem",
    background:
      "linear-gradient(135deg, rgba(255,242,214,0.98), rgba(229,191,135,0.92) 48%, rgba(108,68,30,0.9) 100%)",
    color: "#311705",
    boxShadow: "0 18px 48px rgba(103, 72, 36, 0.18)",
  },
  eyebrow: {
    margin: "0 0 0.5rem",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    fontSize: "0.75rem",
    fontWeight: "700",
  },
  title: {
    margin: "0 0 0.75rem",
    fontSize: "clamp(2rem, 4vw, 3.4rem)",
    lineHeight: 1.05,
  },
  subtitle: {
    maxWidth: "700px",
    margin: 0,
    lineHeight: 1.7,
    fontSize: "1rem",
  },
  section: {
    marginBottom: "1.5rem",
    padding: "1.5rem",
    borderRadius: "24px",
    backgroundColor: "#fffaf2",
    border: "1px solid #eddcc5",
  },
  sectionTitle: {
    margin: "0 0 1rem",
    fontSize: "1.4rem",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    marginBottom: "1rem",
    flexWrap: "wrap",
  },
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "1rem",
  },
  statCard: {
    padding: "1.2rem",
    borderRadius: "20px",
    backgroundColor: "#ffffff",
    border: "1px solid #ecdcc8",
    boxShadow: "0 10px 24px rgba(67, 41, 18, 0.06)",
  },
  statLabel: {
    display: "block",
    marginBottom: "0.45rem",
    color: "#7f4f24",
    fontSize: "0.9rem",
    fontWeight: "700",
  },
  statValue: {
    fontSize: "1.8rem",
    fontWeight: "800",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0.9rem 1.25rem",
    borderRadius: "999px",
    border: "none",
    backgroundColor: "#7f4f24",
    color: "#fffaf4",
    cursor: "pointer",
    fontWeight: "700",
    textDecoration: "none",
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0.8rem 1.1rem",
    borderRadius: "999px",
    border: "1px solid #cdb597",
    backgroundColor: "#ffffff",
    color: "#5c4634",
    cursor: "pointer",
    fontWeight: "700",
    textDecoration: "none",
  },
  dangerButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0.8rem 1.1rem",
    borderRadius: "999px",
    border: "1px solid #d9a198",
    backgroundColor: "#fff1ef",
    color: "#9f2d1f",
    cursor: "pointer",
    fontWeight: "700",
  },
  filterRow: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  input: {
    flex: "1 1 240px",
    minWidth: "220px",
    padding: "0.9rem 1rem",
    borderRadius: "14px",
    border: "1px solid #cdb597",
    fontSize: "1rem",
    backgroundColor: "#ffffff",
  },
  textarea: {
    minHeight: "150px",
    resize: "vertical",
  },
  form: {
    display: "grid",
    gap: "1rem",
  },
  fieldGroup: {
    display: "grid",
    gap: "0.5rem",
  },
  fieldLabel: {
    color: "#5b412d",
    fontWeight: "700",
  },
  inputError: {
    border: "1px solid #d46c5f",
    boxShadow: "0 0 0 3px rgba(212,108,95,0.14)",
  },
  fieldError: {
    margin: 0,
    color: "#b42318",
    fontSize: "0.9rem",
    fontWeight: "600",
  },
  twoColumnGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "1rem",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "1rem 1.1rem",
    borderRadius: "18px",
    border: "1px solid #ecdcc8",
    backgroundColor: "#fffdf8",
  },
  helperText: {
    margin: 0,
    color: "#725b49",
    lineHeight: 1.6,
  },
  list: {
    display: "grid",
    gap: "1rem",
  },
  productCard: {
    display: "grid",
    gridTemplateColumns: "150px minmax(0, 1fr)",
    gap: "1rem",
    padding: "1rem",
    borderRadius: "22px",
    backgroundColor: "#ffffff",
    border: "1px solid #ecdcc8",
    boxShadow: "0 12px 32px rgba(67, 41, 18, 0.08)",
  },
  imageWrap: {
    overflow: "hidden",
    borderRadius: "18px",
    minHeight: "140px",
    background:
      "linear-gradient(135deg, rgba(255,245,228,0.95), rgba(240,216,183,0.92))",
  },
  image: {
    width: "100%",
    height: "100%",
    minHeight: "140px",
    objectFit: "cover",
    display: "block",
  },
  imagePlaceholder: {
    minHeight: "140px",
    display: "grid",
    placeItems: "center",
    color: "#8d6f55",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  productBody: {
    display: "grid",
    gap: "0.85rem",
  },
  productMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.6rem",
    alignItems: "center",
  },
  categoryBadge: {
    padding: "0.4rem 0.7rem",
    borderRadius: "999px",
    backgroundColor: "#f3e2cd",
    color: "#7f4f24",
    fontWeight: "700",
    fontSize: "0.85rem",
  },
  statusBadge: {
    padding: "0.4rem 0.7rem",
    borderRadius: "999px",
    fontWeight: "700",
    fontSize: "0.85rem",
  },
  statusActive: {
    backgroundColor: "#dff7e6",
    color: "#0e6245",
  },
  statusInactive: {
    backgroundColor: "#fbe6d7",
    color: "#9a4d14",
  },
  stockBadge: {
    color: "#6b5a4f",
    fontSize: "0.9rem",
  },
  productTitle: {
    margin: 0,
    fontSize: "1.3rem",
  },
  productDescription: {
    margin: 0,
    color: "#5f5147",
    lineHeight: 1.7,
  },
  productFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "1rem",
    flexWrap: "wrap",
  },
  price: {
    fontSize: "1.1rem",
    fontWeight: "800",
    color: "#6a3f19",
  },
  actionRow: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
  },
  centeredActionRow: {
    display: "flex",
    gap: "0.75rem",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
  },
  status: {
    padding: "2rem 0",
    textAlign: "center",
    color: "#6b5a4f",
  },
  error: {
    color: "#b42318",
    marginBottom: "1rem",
  },
  success: {
    color: "#0e6245",
    marginBottom: "1rem",
  },
};

export default sellerPageStyles;
